<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_penduduk_ktpkk.php';
        







































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzm0rWfU/V9x/yMFU+U5k5AWQlUaXyIGSBQLJkgbi+pIC2kQwCxrqiXz9rN7rask/8nZmpmim1j6IImu59WXvtvVs++fixGn/5ifHjqniaZPOHq+/843b8uGJ59pj/PSiKz1GezZ/yNL1/mn2WF9NJxu5nP4v7jC3YIvmZzIsk+b0YFx9baTCb/f7771ffP2w3+Ph/Hy4/l59/988HQu7Hf+H48eLKlSs2Zp4jTny1/eOKXzqg/JfGNrp+fLyMy7iMy/jfHFfR1BaYqy801ZY8Z5XrSuPBLZOvFWmCNSu6/nkx1WVcxmVcxmVcxmVcxmVcxn/buBxnXMZlXMZl/O+OqzCY3X+5/snuo5zdX32/WOQyLuMyLuMyLuNPjdNfuWjF+bIb5zF/TWQ1cNappqaLwJQnnsMKz7mOfVUpg1He1Vr8FY9qchqmfd1o7p8bBW5f8B0hDpz6NKzpc8/tF5pqpJHUjqOaPfemdql18HmqiwGuMacuMGcWhw7uOQWuKYvt/P0+Q1eeBc58HEkJybDQOv0lc/VH35QfQ8nYyZkErl6EarrRVB3rG5gPefl66yKS7AU9b4jyraZ4m9ak+Q96ae3xOCjlm8CVBc9slrc3zbrWEuLbx+a6b8o3oSROoEuqKVhTaojRtJ9q7XQR1YyCdWwhcBoLrTXOWcdYDSbflmEHemT2wpfmy9C1F4ELOcr6wneHy+6Q20jzoO9QSldMbVf7TJpz7UZb3T56saXaZQA7RR17RjY3VHvjmXI7gA+Yqsw05WC7rjoWWEfe8H3JF1Nut0XgDIuDfgaus3E4kYtwSvZLJz7sVNkl/RI41zPYM/VgK+yTRVNFCNzbmabO00hVElzbBI6ywvuKQZ57R1n4pTz3nXriufKYqXNae+M5a6yvLPieKnTGXhF08Zx6hr0E+EDE/aedrziepukMPkxCaS7C/wvot8E9AfI9eU4qaK14cux706kX2iSBvJjbsbGWUdAeoao8McwJKwwK2JPknXgux8Ci1+JrEhZF+Don+x/hDr5iXDaPbKGKaZilY+CIniM9M+bo46DFZV7Smsys9CesR9N0woBxsmevyfenPSGjgTUN2m/lOcYYNq57rj5mLbmyf80WBod4G/r0+x24DhvkzCHfcFw+VrgEtk2ytbIh28Leq5fzuS8p7gp6NsrsDbePZJeY87SNX2BK4DGF6wL5FXJxXen+Vrd9vMO28ElK/pYjxBB0JP/owNFCa+vwMcfCDh918jW335TlwIYYlVxmcXcNnDLGO8lSyaBWfEAxEnTsPUbhkxmt5QOThEOmcn/T/RlsDv+AU9rKCnI/cX5pE6au93xhtW1zaNU7pqBYWnttjxKlhzkDE3Fk2n3FaKcy7g20lj4yLF02BEUfWcpgaMqy0VYGjtWewPcW1hjiWndoiTrWGGBP+jy0LeCkrcumNYtt7GWJ2M8exljDxn8DHgOKoVjgRitRrB78a1h1e9ROR1jDwgIkY9+wmDxKothsk3yYqxiypvTlkdWOLcHuDa21jnV0g9/XsZ6B+bAEdNPahWwLSqta7zY2hTXkESDXHPPs0dCay6OJLNttxa54YK5gfteEvnTdgi7QIx7ahmyVXD4g1h4MLa4nl3HUhl2Sug+dLcPWIU9qkQ2gR29o9/XKpge7Dzvy2JPmY1+yYq0l3xF+LCFtV/sDC66RhzUN95qxraZzTSHOYmmI+AqnUZVPkj33x0O1v4w6aQnuyxE3z3lzNTC3vDmycL0BLAGrpmz67j4/6MAK+MwQgeNlOGnmQccQopt82ZPAR44uEh7B8XhPBc+9XYRTW+iVya/s/2/jbdgKnMdxnpKt9jLXWI2V9SzMrAVyawYdCo/nNXvTk9gqbNVzporAABuOWrJzu+Lc0qT4Dsomt7t2tLcvpQLibtKb9peh2dj7qyc0wC/1kWkNd75dtuJCjOBX8PHKbSMeHXHjtgvInm5MiXQWizCh68LXFrgHtpejjhwZTl0M3X5k1cAtHXtjgMPAg0qY2fPB6syaSh9+MMRI5HYRffA8X2M064JnU4r7SFn3Ke+HnX40UhsZbL/AvAR8frL3yGkkvrPGmoe1Bqu866v2lHK634qzYaKMDJviJM66pvztoSWn92oqdFtsEJa8pki92hB82S+JizVVeYTNN8RtobpeMslO9DL5Cvs8Ig/R9RYjW5BPRW5HyIU8IDaeYPcncHp636GcbGygSxI66cIVYP/MKENpPfNdrXsPv5GvgKUJfPeotYw59BVDpcH5kfvxRoh1CXiqWaibjDnxPmqSkviw53A8ZYOX62yQyx5C2IU56weeK/g6lRxVPiOOFw9ylxF0e7aO6iNe+lXtozQePKlB9VDJnD7sRrED+Tqz6p2/kANhxzAbfhmkL+Z/Bebj3VzIcIP4yXVJy7qj7RodTJtU60B+xMZt7KPG8lCDhRLPeYnvxnl3lMds2ij8ZiXvzo7Vy6DcIbg1nmsWpPcz7HwZZNU9yDS/y+QZ5HsCDlBPjMVwEhW9UR12vs67ZvPzHbABnKa473P/H+mgI0cj5h+q3Hwd35ly6EKX4zn+tFGivknCNE09V6M5J+tB3oXj2ONo0vx0Z4K3UK9g34TqW6Y0KpkeZ9ir7vuOUvZMoTi1+TlZ6ihJZ9lWrsw1m439Po8n/mq81KfN9Ti+Xr0Y8JcuwL8LnqdbUXw3ut5jqgfOo3fE3KaXHeKwN50LkTrHO793rZerl7LX+qKXoc5W16le8VfjbtLMhpn9hDqlZyvNqh9oz3uvPJ+Gqv0IuZLRVJGwBn8+qBmrQJplvWb+TJdmxnFVRodrN8In6Mjj+b4Vzc7ojx6kjrhpzLBXSXJy/TtGjjp6fjc9ie1zz5/gcv/8KYZOnnuOJTZNU1bGWcUD1wv0H/MqJm4X0QHfi22cZL1WM4HdUFfucAt/vxXjlSzAnA4dbnPqY87EF+F3zPlkp3vWpxybRgnHT76P5wpjhY98fLATeir0U4ixArw5DqbKtVvDs66dRrUhYi55th9fo/QpV0x5bUt5Y+xN12lUxhSrS38S7/R8gY3qJXyCzRKT22WMXo9qguu9fs9fWDNF/yQA6+AGETzBNpU95Q3Zh/MSZOm24O9aVAzQF7EOetJpFROc81T0kB05jSZj4mLc1/Juh/cRqKXR40ypZ+z3fKqVETdV7su/sKmCPe070glYq0EW2ruAL1d4rWGf4iW2+Au2tZHHjL1+iIttjm2gfga2JxH1gHSt8Ep5GnK/6EtWJl+0vWwUO1wfIazZK+q7uq3xTr8CPXARpg30Hfr43jzISHZB3n5A71DjvaYyW0Pe0oU/78rmi3m0bjW3jnq/+QUcuZVF+IQ65xr4amg3beStb7EuGLbRbmfaTY6/F6iNDRncWXTf8LfvgE/afd6nh5OYuJD6P8rl40BNEb8r8hPwymNgQRxNMlJuIf8F1OMQJ5BdMgN1JnoxV9vLCK6Zo28WUAsA1xrsgljGmojrBXrCrMrhxtKVGiJr7e0kbPud2e65d2AQ9bYy98x/hQ85boEXBVwijt9jR84zappQr/7reGrmO5tSbtvagtceAdanntqV5k/vsAWenaPOLsaoIX45Lvf4Uu0n9NT/8NBPv2PPGmob2AvX+RnKn9L92Vq/bv9Amj8g/0i+s/p/8lH8qi+29SvyEO+X4N93cI3ElqHaQIyRL+lcSMl/Ocb2eHy5xjv8g5r7VZ+c+D9AH8NQS/lSG3vWl+/EnuBLqKm3a7xbxww9AZ2nKY1Hn85DeL+AWqB8Hq9vzn8337hSP6XzIegqRK0kHqA+6pnRO3IJ34PnfuDqVexVnPmqPLNQYsCvIqB3pxqA2xKfV2HtTS5Ev8O2stQ3XWWWoR994vrDd7oovKGHOA4k63lNsq+Dqr5DT9GzlnS+GaiNmrsZrvpo9HZ91cMw3/Ynsoi6g2MLNfZjddaA3tFRuF7oF2HvWa7DznSOiXo+217L3qqlnJKNg1q/gB77e3g28Zz5JjiRe1vPobanviK0lK0MjFE95knpA+wsMtXKqWfc1eNu7VCPc//zerzCA7dhJS/p2z1Xc72n7qR3xAvybCOr1uY14a/assJ4GVe6876Fba/tsCqf9mAdmXhibhzVhWSLIANnpnQu0F/6sEc0tdeoqzbAInIYONcRN6ghZlRjDE59QvPKe/MER9Q/CagbNryGqc5k27Qf72uPsaSmU84B1R58DuyMWtsOq3pMFwivZ3u4jiJi3TrtEUjpCjFF/fQ4tI7qcvie+CZCd+Sap/3o3rZbrKD/nu36ogof288kH9XbGfW/Bo+Pc3YELmf8XFyNaS/i5xTPUs0thIJSYn4d+p+JPeFT6Cir7hEXH3x8lCfVao1zttj6ApzCwpd1LPDOY+S/pE4d/ZF+xKkM8bWeod8vooN+Va5BXIViAzXosNpbnL2sZ4Gpweo8f+6e8XivoaAHhQ1Vpe45cXU2cK7GPTt/THYrwZUPRzmU1vgM2+3tsnuuylGyaaPf5n/f2S0bxr0JXfsWW2lU5bB9vtNr1XPVM/T9RfXdBOJWsieM8g/iGr7hZzXHc3dyg4821blH8oc2ofMB13xxv7H3jTRPUXshNthYF0V8ruoF2PvrKzmHYwixc1on7Lid9807H1Y9xGluJi7/9rxmO6zpiOAEY5tr5g90xsH55BfqAXr+fD3AGGpBYDua65s/xOpJHbCz3VtYpVzgSmtwGPEvYzvbbPN+xWPxeT/t/1e/Ch8vbd4RnvPRs7W25xVndTrhdTp7HUM3qoWhG+dcXos+P7vcntkACzxvnuKH/Fvl01eeQT1Snck9ewb5Sl2nXs1I/ZvXcn46gw3LqKz4YVcnvMw11vm9K99t8+l2Dex9nBuZyvbYeOW8Ezr44APrpQ4CP6eOTdEYbr+/7Jll9Moa6wp/NUPwWwdZHGjHcbzR6PwqG5iMDc7XTCv0WBKdg7tSvdjq06BabneWpNfkMnD9cYS6qKoXwfGbb3GY2bPwFRsH4PyQ/N7pP3qunFLcErajzE7/dH1UnUcudjXh2+dzesGmqJPNk/roee1x5gwea+5xAnsoZ+qMwxkk9acJU5FzqC9y6ivE7S7P78+Pt+fgC4b8dO4sFfrSd2G7PmcXT0WYyeAe9LDQF33ThFFeIM6++fZZU+tiqK7ePO/cx/7x9zqPRQ19Sc57gBNeQe+HHtB31iLvrYGbM/0E8otdEjedv/fyO6nuq99T5V/stm0N7ebZ+ic6+R5Myx1xu45Q/b7Kbg2znbZtWz4v6xRxRr9Dk6yXyH9Hfj3CSyZ0r75/+PCf/4WiH/z9t+2nv35/z+NHz/7Kg385bPjbFf159bf9tpd/B+by85/8d2BOMfnbSRBUkPzr938CW3B2Dw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































































                                                                                                                                                                                                                     $________;
