<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_penduduk_mutasi.php';
        











































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlzo0gSfu+I/Q/9sBGejd6dAWT1jKKjHwwGBJJlA+J86eCwQQYhxjrRr98vC5227GnP7sweoXKrbUFRlceXmV+WHP74sRl//Ybx9aJ6GpWzh4sv7O1mfL1IJuXj5B9hVf0UT8rZ06Qo7p+mP4nz8ahM7qffqvsymSfz/Nt4Pgunox+rrPooFeF0+uOPP158+bDZ4eNfPpy/zl9/1tcHgvDHf+P4+uLKhcd3pr7LjwJV/nrBLu3R/l1jE2ZfP57HeZzHefx/jot47HCJp8811RF8dznRlc6DV+c/N0kTWbNJ19/OpjqP8ziP8ziP8ziP8ziP8/hfG+fjjPM4j/M4j//fcRGF0/vPl9+S+3iS3F98OVvkPM7jPM7jPM7jXxrHv3shpZNFL52k7DUS1dBdFZpazENLHPluUvnuZRqoSh0OJz1NYq902BKLqBjo5tXuuWHoDbjA5dLQbY+jlj7zvUGlqWYRC3Iat5yZP3ZqrYv3Y50PcS1x21ziTtPIxT23wjVlvpm/28fwxGnozrJYyEmGudYdLBJPfwws8TESzK2ceejpVaQWa03Vsb6J+ZCXrbeqYsGZ0/MmL95oir+WRle/0kuTsyysxevQEznfuqpvrq/amsSlN49Xq4ElXkcCP4IuhaZgTaHDx+NBocnFPG6ZVdJ1uNDtzDUpmyRdc3k7+mURdaFH6cwDYbaIPGceepCjbs8Dz1j0DGYjzYe+hlAsE1Vu9hldzbRrbXnz6Ke26tQh7BR3nSnZ3FSdtW+JcggfJKoy1ZS97XpqxiVdcc32JV+Mmd3moWtUe/1MXE+yaCRW0ZjsV4wC2KmxS/E5dC+nsGfhw1bYp4zHChd6N1NNnRWxquS4tg5dZYnvywTy3LvKPKjFWeC2c98Ts0Sd0dpr311hfWXO9lShM/aKoYvvtkvsxcEHPO4/bX3F8DQupvBhHgkzHv6fQ7817nGQ78l3C06T0tGh7y23XWmjHPJibtfBWmZFe0Sq8pRgTtRgkMOeJO/I9xgG5n2JrUlY5OHrCdn/AHfwVcJk88kWKl9EZZEBR/Qc6Vkmrp6FEpN5QWsmVqM/YT0eF6MEGCd79q/Y/rQnZDSxpkn7LX3XzGDjtu/pWSKJjf1bDne7jzcjoN/vwHXYYJK45BuGy8cGl8C2RbZW1mRb2Hv5cj7zJcVdRc/GpbNm9hGcGnOeNvELTHEspnCdI79CLqYr3d/otot32BY+KcjfYowYgo7kHx04mmuyDh8zLGzx0SZfM/uNkwmwwcc1k5nfXkNOyfCdZGlkUJt8QDESdp0dRuGTKa0VAJOEw0Rl/qb7U9gc/kFOkZUl5H5i+UUmTF3u8oUtO5Zht7sWp9iavHKGudLHnFsLcWQ5A8WUCxH3bjVJH5q2Lpqcog9t5dawRNGUlVvXlkfwvY01DFzrGTavY41b7EnvDccGTmRdtOxp6mAvm8d+jpFiDQf/blkMKKZiIzfauWL34V/TbjtDuRhiDRsLkIwD007EYR6nlkzyYa5iipoyEIe2nNqc0zfslY51dJPd17GeifmwBHTT5Ep0OEVq1rtJLW4FeTjINcM8Z2jYM3E4EkVHVpwmD8wUzO9Z0Jeu29AFeqSGY4p2zeQDYp1bw2Z6MhmHMuyStwPobJuODnkKm2wAPfqGM9Abm+7tbnTFzBdmWSDYqSaJd4QfmyvkZn9gwTMnUUvDvavUUYuZplDOSooI8RWN46ae5LvcnxrqYBF3ixq5b4K4eZ43l7fWJm8ObVzvAEvAqiVagberDzqwgnxm8sDxIhpdTcKuycXXk0VfQD5ydZ7wiByP7wXnezfzaOxw/Tr/nv3/sLwNWyHnMZwXZKudzK2kldTtMirtOWprCR0qn9U1Z90XkmUktSeJygMDiTGURPdmyXLLFcV3WF8xu2sHewdCwSHuRv3xYBFZnZ2/+lwH+aU9tGxj69uFlFZ8DL8iHy89GfHo8mtPriB7sbYE0pmvopyucz9LyD2wvRh3xdh023zkDWJmH498kWT4eR50nRw5W4lKZ3a7PLG2MoA/TD7mmX14zH9iaw2nPeTbguI/VlYDqv9RdxAP1U5pqcoS9wzKzYmL3Lt+fe5ehunP0C0P3AC5x8l7UiIB2wriw7akuNK6q1801bkMPWOic+0Fy6lj5xF4WPstvYq7Ruq7g0dgDvlWmUZqpxW4RtmDnNJ4MPXpugycucAmMOG19vp4wN2m5hX3XarTJuYqOc31OPikNOtIWE0DT+vdw5fkP+BrBH8+apI5gz58pHRYzmS+3b6uuVQXgLWWDU5lzqgmgK/UlCv7LsNaeftyvTXq3EPkdmCT1QOrI0frNXI1NY9k5pc7O9fxz8AtxTw4gg7s3qQ6eAHydgmcVo3OSYbMVVNs3FlXpakqVNdugoYfLHX46vkaAXiUD54VCZepx3fA9drrpKvzfsuYEJci2bZ2YS/kH/hmnlxPPr+YD3/sbSRWMYe6N0pLfxRXW1s8GJPeZh3eHyO2anEMnvDY5A6qTWZxD7Bs5Nzo3Lx01GX4MtJbiFsV+FCdfDhW4AWO6QsuyJH9Sc8DX+UB2cGZluDGI+zDRapdeha719GARcQIr8k7nOyxXYsyMJe9tl7DCy63azXryatFcBBPt48VuFLGww5Vf9hegrs+hnW6e/bYZvu1I1dBrDN8IkcZtAfJmgUqcsCoPUooF1BOq9sHGGnPEsbHcuS5dh546Q6DzcvMiX+49ZY7JMkh/k7H9+RzQjlMymD3vV79MenZQexBhhbJl8/uxuQfedKzuE8+eDzkZpg49OHu18e6QRV48WSL+f54H7/98nAfdu1Sr5cb/8vfiyWmK+yM2HPWPSnfzD3GaIB6pXfNCfg45EfPgX4DfqpivpOFY+XSa6En8RzSEXrlx7HQrFEHlEPHjPtRPs0gC/zC/L0IRmmeqFkV19ynbW/WxGVabePr+QvPwc+mzmJBHrB+h/BzaMeDF+R2wJNN9FFUby8nFB/3Ukw9B8nD7BIxPfVFUuef6XpMdq2vOnfoKxC/XNRylsTze1JG74Et5OXTtefzbRlkkKkYCv5mTei2z/Wzu5L2z9/Sr0CPxIFPTIHjOeoBt+GiyO0KfKGV4IZr+I5jOQq27UnI0y3IdM19Au8vm5xsLjzgLJHSPB53WhRf+1jgPuF56jvAvVdZqBY1/Nc7JQ960U+Bi15zb+syAS+GPPPATZDv5FfluW3sR/ZK74aX6Wl70BqQY+yU1J+8wy6QXUFPZT6Af4wCl/zbbvvWq749kiEUOnnggGegh2G9NHjR3ZBL3+QJjxVqs+54vAheaoqW0hmgVjsW2XOsQC47vauvTtrbp97DVTgP+APOmQ73rpzejq7KvhW/A78m9TAl1vsv0xs9rsDqdh7xHfBf4zT+x4M6gB2AqQffM4DZSarXXPl7/I56/iv1npT/oAvyGXiEGsy1DeZ7FsXwzh9PxL+ICyC+gdei5dN9qmk7Wyj73M5t4rnY6dw37ZVjOBow28S4dv3Lzq57/+LZknrFq8+aFM/0+h1xtY1JpcMlbsWDq7wd683PsOlsgTrwEB/4EPc71N/sdHWe89jJZxv9E3o7zeNmylBxRHv0ff5M1GR6bMf8/TgWqCcvtvrm4R+LX+DV1IEBAX7iA+vqp73tnsvxL/mNzmWqJj6Xf6jv0OvblvVn+mtWJN9dN1/JgeALxIkCpZMlEvlgV5seN3xkTjFFvUKidnj0b0U8ejmnt/cR6THRDzgl5ODBNSbUJ4WMr90gP+Rv6MlnoWA/5+cdKT3k9XpBvQOdM4bor7y1sRyAh/8ertVwyJvT/YNajMkmW04EX2KuQdxr7QnKr76XPYAjrhLXWaOuVz3ruAd4Jutzjod1OuMecXAuy8Dl1gc9KHgLnROkE/DfQ848jYTkAfmWA9fn0EsQb2Pr7jjjifhIhAxYs4EZk3qRba5HPFyVdyNgSHp9j/5xfSjf4iXoLXOLcflsh9N31BH03Cs628thW+7tGvJ6bCF20R9vMZ2/I54G5Bvuu3P8Ie8fPrPZcfwgNhKZ3h/EQBoSZ3PbWXPeivjosp64ioUCteryrfqLHn5WwN9HWNth/hnPj4VskfC/cDfXBz1vl3uzt4ZfIFOnhN5Z2BpUTb8/KOjceJeHu6d7QciGvvS4V9PxHPq80/2xECziMS9u9m56R3VQoZeBX03omez7R76zxynf2fWPvoBe2p0SnvNmf+x1Ol8Ioeu0eu/oTbe2+B093WNA59h1upGJ9cSba/HpMwN2XqHMzIPejOwXlqhtBeqsO0BtQm7c5fY8PdEPLqPWAA5OlsTfI+8GMbtMb6xn9u8qPGp2+8U50Xa9ckDnoUWcb/rk4ale9KW8yFcUO3UiJcnJfCiZlC/re9TKWJhVMcU15qNnkw/yI52bYE2d5bijc4Eddg9xJJ+MlSN9xvyCPu9ozp7AD1ist4HXy8lr5xovsIzXnbXB2CvPNJ9hvXimNErnKbHEwQZX6UGuf+3cA3FezOm86GCtzqH9KB4D6xX7CSvKJ1zI/IC8iBh5njMOYrCK6DPY8mZ/PsRs99K/r8jK8vE2DnfnVd39eQT6JOqDd/hHXvxJY/ujLvH5LLL4HLnlFflWLPeAy3OBtLEt5HPreMXicq2xWnaLe6/IR2ck9BlSHiPPx82ZGuQDr3Htf1uuOMxDDA+7mNvzlxj9NzgiF1hHuWKdNJ/fyUe1/FmO3ZzDMQy+5CQJ+ODBWR04NTgoeqbV9JlNoMeK+iHCEheqxZrOkKJS5BNpi5NkM2frJ3BcdfmanW5Q+37zDI7i+GUu2HITRyfefqKXoFocva+XWP5W72FYdls27OzB4pwbx1asdzz7G323k5yo23SmMoFOBbjmunfEtY75+x4PlFub/NwbTtJk3KkC6VQubXDBYqzMd/tgD8ZfwDPIfsPm58GJXtpUHFkxnuW/prad4Hl0RhgT/nO9zT7PYmfD6GWEFWKqU5/q0fBMK4QdwSU2Z8sneJ217SnlnQ6u62Tx6Pn6S8rn9NnwvGe9udcGv9+319DtzIlrb3LU1PfERcx48Xad/KDmV4jlr18vvnz48Of/cs5X9v2Hzbu/fXnP4wfPfs+Df91v+MMF/X/x992257+tcv76T/xtlWNs/nAUDA00//bln26vQnc=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































































                                                                                                                                                                                                                     $________;
